apiVersion: v1
entries:
  mychart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-07T16:47:25.968464122+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.6.25
    description: A Helm chart for Kubernetes
    digest: 7c3707a6cb711679c93397dfdc84cf5d874ed9e9088547945e53add227334706
    name: mychart
    type: application
    urls:
    - mychart-0.1.3.tgz
    version: 0.1.3
generated: "2022-08-07T16:47:25.963777566+02:00"
